# process_fastqs.smk
import glob
import os

configfile: "config/config.yaml"

FASTQ_DIR = config["fastq_dir"]
FASTQS = glob.glob(os.path.join(FASTQ_DIR, "*.fastq.gz"))
SAMPLES = [os.path.basename(f).replace(".fastq.gz", "") for f in FASTQS]
OUTDIR = config["output_dir"]
HGREF = config["hg38_ref"]

rule all:
    input:
        expand(f"{OUTDIR}/QC/{{sample}}_fastqc.html", sample=SAMPLES),
        expand(f"{OUTDIR}/alignments/{{sample}}.mark.bam", sample=SAMPLES)

include: "rules/process_fastqs.smk"
include: "rules/align_fastqs.smk"
