sample_sheet: "/opt/data/cnakagawa/snk-chip/samplesheets/test.csv"
hg38_ref: "/opt/data/genomic/references/HomoSapiens/hg38/Homo_sapiens_assembly38.fasta"
output_dir: "/opt/data/cnakaChIP/Results/tempalltest"

